version: "3.0"
services:
    web:
        image: wordpress
        ports: 
            - "80:80"
            - "443:443"
            
        environment:
           WORDPRESS_DB_HOST: db:3306
           WORDPRESS_DB_USER: wordpress
           WORDPRESS_DB_PASSWORD: wpPassWord45
           
        networks:
            - webnet
    db:
        image: mariadb
        
        environment:
           MYSQL_ROOT_PASSWORD: uncrackable23pass
           MYSQL_DATABASE: wordpress
           MYSQL_USER: wordpress
           MYSQL_PASSWORD: wpPassWord45

        volumes:
           - db_data:/var/lib/mysql

        networks:
           - webnet
           
volumes:
    db_data:
    
networks: 
    webnet:
