version: "3.0"
services:
    web:
        image: wordpress
        ports: 
            - "80:80"
            - "443:443"
        networks:
            - webnet
    db:
        image: mariadb

        networks:
            - webnet
networks: 
    webnet:
